[package]
name = 'dalted'
version = "0.1.0"
authors = ["$www.steadylearner.com"]
edition = "2018"

[dependencies]
rocket = "0.4.4"
tera = "0.11.20"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
image = "0.23.2"
base64 = "0.12.0"

[dependencies.rocket_contrib]
version = "0.4.4"
default-features = false
features = ["tera_templates", "json"]

# template and markdown
tera = "0.11.20"
