[package]
name = "dalted-actix"
version = "0.1.0"
authors = ["carrascomj <carrascomurielj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.7"
tera = "1.0"
actix-http = "1.0.1"
actix-web = "2.0.0"
actix-rt = "1.0.0"
serde_derive = "1.0"
serde = "1.0"
actix-files = "*"
image = "0.23.2"
failure = "*"
futures = "*"
future-utils = "*"
imageproc = "0.20"
base64 = "0.12.0"
